#######################################################################################
# Book settings
title: AST4007W Computational Methods
author: Luis A. Balona, Ed Elson, Masimba Paradza and Mayhew Steyn
logo: images/UCTcircular_logo.png

description: >-
  Course notes for the NASSP Honours Computational Methods module at the University of Cape Town.

only_build_toc_files: true

#######################################################################################
# Launch button settings
repository:
 url: https://github.com/maystey/uct-nassp-cm-2021
 path_to_book : book

#######################################################################################
# HTML-specific settings
html:
 use_repository_button: true
 use_issues_button: true

#######################################################################################
# Sphinx settings
bibtex_bibfiles:
  - _bibliography/references.bib

######################################################################################
# MyST Markdown settings:
parse:
  myst_url_schemes: [mailto, http, https]
  myst_enable_extensions:
    - colon_fence
    - dollarmath
    - linkify
    - substitution

    - amsmath
    - html_admonition


######################################################################################
# Exclude
exclude_patterns:
  - pdf_book
  - content/scientific-packages/numpy/special-functions.ipynb
  - content/numerical-methods/root-finding/utils.py
  - content/numerical-methods/regression/notation.md
